[TOC] 
main_font_size = "12px"
main_indent = "1em"
main_margin = "0.5em"

chapter_font_size = "18px"
chapter_indent = "3em"
chapter_margin = "1em"

[wkhtmltopdf]
dpi = 120
footer-font-size = 7
page-size = "A4"
margin-top = "0.6cm"
margin-bottom = "0.6cm"
margin-left = "2cm"
margin-right = "2cm"

footer-right = "[page]/[topage]"
zoom = 0.8
disable-smart-shrinking = true
dump-outline = "outline"
encoding = "UTF-8"
footer-line = ""
quiet = ""
disable-javascript = true